// Fake texts per occupation for the demo. "Me" is the phone owner. No real messages.
const SAMPLE_CHATS = {
  'Tennis coach': { emoji: '🎾', messages: [
    ['Jake', 'lesson tomorrow at 4?'],
    ['Me', 'yep! and court booked for thursday too'],
    ['Priya', 'hey can we reschedule to saturday? kid has a recital'],
    ['Priya', 'also how many lessons left in the package'],
    ['Me', 'let me check the spreadsheet, one sec'],
    ['Dan', 'paid via venmo for this week 👍'],
    ['Maria', 'Hi! my son wants tennis lessons, do you have any openings?'],
    ['Maria', 'and how much does it cost?'],
    ['Tom', 'so sorry, missed our session today, work ran late'],
    ['Me', 'no worries! still waiting on payment for last week btw'],
    ['Tom', 'omg forgot to pay you, sending now'],
    ['Jake', 'can you fit me in this weekend'],
    ['Me', 'honestly so hard to keep track of everyone rn'],
    ['Priya', 'same time next week?'],
  ]},
  'Tutor': { emoji: '📚', messages: [
    ['Mrs. Chen', "how'd the quiz go?"],
    ['Me', "good! she's struggling with fractions again though"],
    ['Mrs. Chen', 'can we do an extra hour before the exam'],
    ['Me', 'yes, next session tuesday 5pm'],
    ['Ben', 'i need to catch up on chapter 4 before the test'],
    ['Me', 'sent over the worksheet for tonight'],
    ['Ben’s dad', 'his mom and I talked, the other parent asked for a progress update'],
    ['Mrs. Chen', 'same rate as last month?'],
    ['Lily’s mom', 'her exam is next tuesday, can we add a session?'],
    ['Me', 'are you free thursday at 6?'],
    ['Lily’s mom', "yes! don't let me forget to pay you for last month"],
    ['Me', 'haha i keep forgetting who paid honestly'],
  ]},
  'Hair stylist': { emoji: '✂️', messages: [
    ['Ashley', 'do you have anything open saturday?'],
    ['Me', 'I have 11 or 2'],
    ['Ashley', '2 please! how much for balayage'],
    ['Me', '$180, deposit required to hold it. here’s my venmo'],
    ['Kim', 'running 10 min late sorry!!'],
    ['Jess', 'need to cancel my appointment tomorrow 😭'],
    ['Me', 'no problem, can we reschedule for next week?'],
    ['Nina', 'confirming my 2pm friday'],
    ['Tara', 'saw your work on insta! do you have availability next month?'],
    ['Maddie', 'slow week at the salon, we need more bookings'],
    ['Me', "i know, i haven't posted in a while"],
    ['Maddie', 'post the new style pics! flash sale this weekend?'],
  ]},
  'Landlord': { emoji: '🏠', messages: [
    ['Carlos (2B)', 'rent is late again sorry, can i pay half now half later?'],
    ['Dana (4A)', 'sent the rent!'],
    ['Dana (4A)', 'also the ac is broken again'],
    ['Me', "ok i'll look up an hvac guy today"],
    ['Mike (1C)', 'lease renewal coming up, can you send over the details?'],
    ['Me', 'will do, need to write up a contract anyway'],
    ['Carlos (2B)', 'zelle sent for the first half'],
    ['Carlos (2B)', 'do i need a receipt for that'],
    ['Dana (4A)', "when's rent due next month, the 1st?"],
    ['Me', 'got 3 quotes for the roof, not sure which to pick'],
    ['Sam', 'did you ever get the paperwork back from 1C'],
    ['Me', "no, i'm so behind on paperwork. need to see where we stand financially"],
  ]},
  'Student': { emoji: '🎒', messages: [
    ['Maya', 'exam is next tuesday right??'],
    ['Me', 'yes and a quiz on friday 😭'],
    ['Leo', 'study group at the library at 6?'],
    ['Me', 'yes. did you finish the reading'],
    ['Leo', 'lol no. notes for chapter 5?'],
    ['Me', "i'll send you the doc"],
    ['Maya', 'also the project due at midnight wednesday'],
    ['Me', 'and i have to present this thursday, need slides for class'],
    ['Leo', "don't let me forget the lab report"],
    ['Maya', 'which one should i buy for school, ipad or laptop'],
    ['Mom', 'are you free sunday for dinner?'],
  ]},
  'Friend group': { emoji: '💬', messages: [
    ['Maya', 'ok are we still doing dinner friday'],
    ['Priya', 'yes!! where should we go'],
    ['Tyler', 'i dont care honestly'],
    ['Maya', 'omg someone just pick'],
    ['Priya', 'which is the better deal, the thai place or burgers'],
    ['Maya', 'ok bill was $112 so $28 each'],
    ['Maya', "jordan you haven't paid yet lol"],
    ['Priya', 'spring break trip is coming up!!'],
    ['Jordan', "can't decide on a destination tho"],
    ['Maya', 'we need an itinerary, what should we do each day'],
    ['Tyler', 'remind me to book the airbnb'],
    ['Priya', "don't let me forget sunscreen"],
    ['Maya', 'are you free saturday to plan?'],
  ]},
};

if (typeof module !== 'undefined') module.exports = SAMPLE_CHATS;
